export enum Specialities {
  CARDIOLOGIST = "cardiologist",
  FERTILITY = "fertility",
  MENTALHEALTH = "mentalHealth",
  NEUROLOGY = "neurology",
  ORTHOPEDIC = "orthopedic",
  UROLOGY = "urology",
  ONCOLOGIST = "oncologist",
  NEONATOLOGIST = "neonatologist",
  ORTHOPEADIC = "orthopeadic",
  DIETRICIAN = "dietrician",
  COSMETIC = "cosmetic",
  PSYCHIATRIST = "psychiatrist",
  PAEDIATRIC = "paediatric",
  COLO = "colo",
  NUTRITIONIS = "nutritionist",
  PHYSIOTHERAPIST = "physiotherapist",
  ENT = "ent",
  DENTIST = "dentist",
  DERMATOLOGIST = "dermatologist",
  RADIOLOGIST = "radiologist",
  NEPHROLOGIST = "nephrologist",
  ANAESTHESIOLOGIST = "anaesthesiologist",
  ENDOCRINOLOGIST = "endocrinologist",
}
