export const SpecialityList = [
  { id: "general_medicine", name: "General Medicine" },
  { id: "fertility_specialist", name: "Fertility Specialist" },
  { id: "oncology", name: "Oncology" },
  { id: "physiotherapy", name: "Physiotherapy" },
  { id: "mental_health", name: "Mental Health" },
  { id: "paediatric_specialist", name: "Paediatric Specialist" },
  {
    id: "gynaecology_obstetrics_specialist",
    name: "Gynaecology & Obstetrics Specialist",
  },
  { id: "physiotherapist", name: "Physiotherapist" },
  { id: "urologist", name: "Urologist" },
  { id: "dermatologist", name: "Dermatologist" },
  { id: "neurologist", name: "Neurologist" },
  { id: "cosmetic_surgeon", name: "Cosmetic Surgeon" },
  { id: "endocrinologist", name: "Endocrinologist" },
  { id: "neonatologist", name: "Neonatologist" },
  { id: "oncologist", name: "Oncologist (Cancers)" },
  { id: "orthopaedic_specialist", name: "Orthopaedic Specialist " },
  { id: "anaesthesiologist", name: "Anaesthesiologist" },
  { id: "nephrologist", name: "Nephrologist" },
  { id: "psychiatrist", name: "Psychiatrist" },
  { id: "radiologist", name: "Radiologist" },
  { id: "nutritionist", name: "Nutritionist" },
  { id: "dietician", name: "Dietician" },
  { id: "dentist", name: "Dentist" },
  { id: "colo-rectal-specialist", name: "Colo-Rectal Specialist" },
  { id: "ent-specialist", name: "ENT Specialist" },
  { id: "other", name: "Other" },
];
